# Header

title: iHTCboy's blog
subtitle: 'Learn something of everything,  Learn everything of something.'
description: ""
author: iHTCboy
keywords: "iOS,Swift,Object-C,Flutter,Android,Java,Developer,Apple,Python,Life"

menu:
  首页: /
  归和档: /archives
  技和术: /categories/technology
  总和结: /categories/induction
  # 笔和记: /NotesEveryDay/
  生和活: /categories/life
  诗和意: /categories/poetry
  更和多: /more
#  随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/iHTCboy"
  twitter: "https://twitter.com/iHTCboy"
  weibo: "https://weibo.com/iHTCapp"
  zhihu: "https://www.zhihu.com/people/iHTCboy"
  #bilibili: "https://space.bilibili.com/472002243"
  weixin: "https://mp.weixin.qq.com/s/XPG9j6Rb8kdhe9TbtM5zpQ"
  mail: "mailto:ihetiancong@gmail.com"
  rss: "https://iHTCboy.github.io/atom.xml"
  #  jianshu: "http://www.jianshu.com/users/893e02c03bbc"
  #zhihu: "#"
  #qq: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '显示全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '如果喜欢，欢迎分享点赞，扫一扫鼓励，用心创作创新！'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/weixinpay.jpg


# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: '054dcc78aa7e685b4e12991f3e56ebd6'
google_analytics: 'UA-67136970-2'
favicon: /img/favicon.png

#你的头像url
avatar: https://ihtcboy.com/img/favicon.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false
#changyan_appid: 'cytu3vPiW'
#changyan_conf: 'prod_5348e762f7a9ee897f4acf2f5c140daf'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: iHTCboy #11418363      #你的 GitHub ID
gitment_repo: 'iHTCboy.github.io'          #存储评论的 repo
gitment_oauth:
  client_id: 'ba571dc501cf1963fff8'           #client ID
  client_secret: '9340cd4031280da2640c0c983d359d08aad3c385'       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg, #6db6bb, #103e56)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '搜索'
  friends: '友链'
  aboutme: '关于'

friends:
  GitHub: https://github.com
  Apple Developer: https://developer.apple.com
  Android Developers: https://developer.android.com
  Google Developers: https://developers.google.com/?hl=zh-cn
  Ray Wenderlich: https://www.raywenderlich.com
  Stack Overflow: https://stackoverflow.com
  objc.io: https://www.objc.io
  objc 中国: https://www.objccn.io
  NSHipster: https://nshipster.com
  NSHipster 中国: https://nshipster.cn
  Swift.org: https://swift.org
  We ❤ Swift: https://www.weheartswift.com
  SwiftDoc.org: https://swiftdoc.org
  Swifter.tips: https://swifter.tips
  Go: https://golang.org
  Dart: https://dart.dev
  Flutter: https://flutter.dev
  React Native: https://reactnative.dev
  WEEX: https://weex.apache.org/zh/
  微信开放文档: https://developers.weixin.qq.com/doc
  宇宙湾: https://yuzhouwan.com
  Climate2Weather: http://climate2weather.cc



aboutme: iHTCboy <br> 破得迷，了得知，方能学海无边；<br> 热爱移动开发，自动化<br><br> 一花一世界，一木一浮生，<br> 一草一天堂，一叶一如来，<br> 一砂一极乐，一方一净土，<br> 一笑一尘缘，一念一清静
